version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}"
  build:
    commands:
      - ls -l .
      - docker build -t fujikomalan/codebuildapp:latest -t fujikomalan/codebuildapp:${CODEBUILD_BUILD_ID} .
      - docker image ls
      - docker push fujikomalan/codebuildapp:latest
      - docker push fujikomalan/codebuildapp:${CODEBUILD_BUILD_ID}
  post_build:
    commands:
