version: 0.2

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout -t 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}"
  build:
    commands:
      - whcih docker
      - which dockerd
      - netstat -ntlp
      - ls -l /var/run/docker.sock 
      - ls -l .
      - docker build -t fujikomalan/codebuildapp:latest .
      - docker image ls
  post_build:
    commands:
