version: 0.2

phases:
    install:
      commands:
        - cat /etc/os-release
        - which docker
        - which dockerd
        - netstat -ntlp
        - ls -l /var/run/docker.sock 
        - ls -l .
        - timeout -h
    pre_build:
      commands:
        - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}"
    build:
      commands:
    
    post_build:
      commands:
