version: 0.2

env:
  variables:
   OS: Linux
   PACKAGE: apach2

phases:
  install:
    commands:
  pre_build:
    commands:
  build:
    commands:
      - cat /etc/os-release
      - ls -l /boot
      - free -m
      - docker version
      - docker image ls
      - docker info
  post_build:
    commands:
