version: 0.2

phases:
  install:
    commands:
  pre_build:
    commands:
      - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}"
  build:
    commands:
      - ls -l .
      - docker build -t fujikomalan/codebuildapp:latest .
      - docker image ls
  post_build:
    commands:
